name: dp_graph_classification
name: dpgnns
channels:
  - pytorch
  - conda-forge
  - pyg
  - anaconda
  - esri
  - pip
dependencies:
  - pytorch::pytorch=1.12
  - conda-forge::cudatoolkit
  - conda-forge::torchmetrics=0.10.3
  - conda-forge::scikit-learn
  - conda-forge::pandas
  - conda-forge::wandb
  - conda-forge::seaborn
  - conda-forge::matplotlib=3.5.1
  - conda-forge::jupyterlab
  - pyg:pyg
  - pyg::pytorch-cluster
  - conda-forge::scikit-learn=1.1.2
  - conda-forge::opacus=1.1.2
  - conda-forge::ogb
  - conda-forge::wandb
  - pip:
    - functorch==0.2.0
